# coding: utf-8

"""
    Blockscout ENS

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Contact: support@blockscout.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.v1_address import V1Address
from openapi_server.models.v1_protocol_info import V1ProtocolInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class V1Domain(BaseModel):
    """
    V1Domain
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    resolved_address: Optional[V1Address] = None
    owner: Optional[V1Address] = None
    wrapped_owner: Optional[V1Address] = None
    registration_date: Optional[StrictStr] = Field(default=None, description="Optional. RFC 3339 datetime of expiry date.")
    expiry_date: Optional[StrictStr] = None
    protocol: Optional[V1ProtocolInfo] = None
    __properties: ClassVar[List[str]] = ["id", "name", "resolved_address", "owner", "wrapped_owner", "registration_date", "expiry_date", "protocol"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1Domain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of resolved_address
        if self.resolved_address:
            _dict['resolved_address'] = self.resolved_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wrapped_owner
        if self.wrapped_owner:
            _dict['wrapped_owner'] = self.wrapped_owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of protocol
        if self.protocol:
            _dict['protocol'] = self.protocol.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of V1Domain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "resolved_address": V1Address.from_dict(obj.get("resolved_address")) if obj.get("resolved_address") is not None else None,
            "owner": V1Address.from_dict(obj.get("owner")) if obj.get("owner") is not None else None,
            "wrapped_owner": V1Address.from_dict(obj.get("wrapped_owner")) if obj.get("wrapped_owner") is not None else None,
            "registration_date": obj.get("registration_date"),
            "expiry_date": obj.get("expiry_date"),
            "protocol": V1ProtocolInfo.from_dict(obj.get("protocol")) if obj.get("protocol") is not None else None
        })
        return _obj


