# coding: utf-8

"""
    Blockscout ENS

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Contact: support@blockscout.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class V1Order(str, Enum):
    """
    V1Order
    """

    """
    allowed enum values
    """
    ORDER_UNSPECIFIED = 'ORDER_UNSPECIFIED'
    ASC = 'ASC'
    DESC = 'DESC'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1Order from a JSON string"""
        return cls(json.loads(json_str))


