# coding: utf-8

"""
    Blockscout ENS

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.3.0
    Contact: support@blockscout.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class V1ProtocolInfo(BaseModel):
    """
    V1ProtocolInfo
    """ # noqa: E501
    id: Optional[StrictStr] = None
    short_name: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    deployment_blockscout_base_url: Optional[StrictStr] = None
    tld_list: Optional[List[StrictStr]] = None
    icon_url: Optional[StrictStr] = None
    docs_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "short_name", "title", "description", "deployment_blockscout_base_url", "tld_list", "icon_url", "docs_url"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V1ProtocolInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of V1ProtocolInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "short_name": obj.get("short_name"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "deployment_blockscout_base_url": obj.get("deployment_blockscout_base_url"),
            "tld_list": obj.get("tld_list"),
            "icon_url": obj.get("icon_url"),
            "docs_url": obj.get("docs_url")
        })
        return _obj


