# coding: utf-8

"""
Blockscout ENS

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.3.0
Contact: support@blockscout.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.domains_extractor_api import (
    router as DomainsExtractorApiRouter,
)
from openapi_server.apis.health_api import router as HealthApiRouter

app = FastAPI(
    title="Blockscout ENS",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="1.3.0",
)

app.include_router(DomainsExtractorApiRouter)
app.include_router(HealthApiRouter)
