data-path={{ .Values.dataPath | quote }}
logging={{ .Values.logging | quote }}

host-allowlist=["*"]
min-gas-price=0
min-priority-fee=0
network-id={{ .Values.networkId }}

rpc-http-cors-origins=["*"]
rpc-http-enabled=true
rpc-http-api=["ETH","NET","WEB3","ADMIN","DEBUG","TRACE","TXPOOL","QBFT"]
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

sync-mode="FULL"
data-storage-format="FOREST"

tx-pool="SEQUENCED"
tx-pool-no-local-priority=true

max-peers=25
discovery-enabled=false
p2p-enabled=true
p2p-interface="0.0.0.0"
p2p-port=30303
static-nodes-file="/etc/besu-static/static-nodes.json"
