apiVersion: v1
kind: Service
metadata:
  name: nb-bond-api
  namespace: {{ .Values.namespace | default "nb-bond-api" }}
spec:
  selector:
    app: nb-bond-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
