apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-config
  namespace: {{ .Values.namespace }}
data:
  validator.toml: {{- include "validator-config-toml" . | toYaml | indent 4 }}
  archive.toml: {{- include "archive-config-toml" . | toYaml | indent 4 }}
