apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besu-validator-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.validator.diskSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besu-archive-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.archive.diskSize }}
