apiVersion: v1
kind: Service
metadata:
  name: besu-archive
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: rpc-json-http
      port: 8545
      targetPort: 8545
    - name: rpc-json-ws
      port: 8546
      targetPort: 8546
  selector:
    app: besu-archive
---
apiVersion: v1
kind: Service
metadata:
  name: besu-validator
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: operator-rpc
      port: 8545
      targetPort: 8545
  selector:
    app: besu-validator
---
apiVersion: v1
kind: Service
metadata:
  name: besu-validator-p2p
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: p2p-tcp
      port: 30303
      targetPort: 30303
      protocol: TCP
    - name: p2p-udp
      port: 30303
      targetPort: 30303
      protocol: UDP
  selector:
    app: besu-validator
---
apiVersion: v1
kind: Service
metadata:
  name: besu-archive-p2p
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: p2p-tcp
      port: 30303
      targetPort: 30303
      protocol: TCP
    - name: p2p-udp
      port: 30303
      targetPort: 30303
      protocol: UDP
  selector:
    app: besu-archive
